In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt # matplotlib içerisindeki pyplot modülünü plt olarak import ettik
import matplotlib as mpl # sadece matplotlibi import etmek etmek için kullanırız

import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

In [ ]:
🟢 1. Basit Seviye (5 Soru)

Veri setindeki toplam satır ve sütun sayısını bulun.

İlk 3 satırı görüntüleyin.

Tüm kişilerin ortalama nabız (pulse) değerini hesaplayın.

En uzun süre egzersiz yapan kişinin adını bulun.

Kaç kişi diyet yapıyor?

🟡 2. Orta Seviye (5 Soru)

Diyet yapan ve yapmayanların ayrı ayrı ortalama kalori yakımını hesaplayın.

20 dakikadan fazla egzersiz yapanların ortalama nabzını bulun.

Nabzı 90’dan yüksek olan kişilerin isimlerini listeleyin.

Egzersiz süresi (time) ile yakılan kalori arasındaki ilişkiyi (korelasyonu) hesaplayın.

En düşük kalori yakan kişi kimdir?

🔴 3. Zor Seviye (5 Soru)

Diyet durumuna göre gruplayarak toplam yakılan kaloriyi bulun.

Ortalama sürenin (time) üzerinde egzersiz yapan kişilerin ortalama kalorisini hesaplayın.

Hem nabzı 85’in üzerinde olan hem de 200’den fazla kalori yakan kişileri seçin.

Kişilerin verimliliğini hesaplayın: calories / time → “kalori/dakika” metrik sütunu ekleyin.

En verimli (kalori/dakika değeri en yüksek) kişiyi bulun.

In [2]:
exercise = sns.load_dataset('exercise')
exercise # exercise data setini çağırdı

    Unnamed: 0  id     diet  pulse    time     kind
0            0   1  low fat     85   1 min     rest
1            1   1  low fat     85  15 min     rest
2            2   1  low fat     88  30 min     rest
3            3   2  low fat     90   1 min     rest
4            4   2  low fat     92  15 min     rest
..         ...  ..      ...    ...     ...      ...
85          85  29   no fat    135  15 min  running
86          86  29   no fat    130  30 min  running
87          87  30   no fat     99   1 min  running
88          88  30   no fat    111  15 min  running
89          89  30   no fat    150  30 min  running

[90 rows x 6 columns]